
#define CLTWEET_TIMESTAMP @"created_at"
#define CLTWEET_IN_REPLY_TO_ID @"in_reply_to_status_id"
#define CLTWEET_USER @"user"
#define CLTWEET_BODY @"text"
#define CLTWEET_ID @"id"
#define CLTWEET_UPDATE_STATUS @"status"
#define CLTWEET_MEDIA_HASHTAGS @"hashtags"
#define CLTWEET_MEDIA_URLS @"urls"
#define CLTWEET_MEDIA_MENTIONS @"user_mentions"
#define CLTWEET_MEDIA_URL_DISPLAY @"display_url"
#define CLTWEET_MEDIA_URL_URL @"url"
#define CLTWEET_MEDIA @"entities"
#define CLTWEET_RETWEETED_TWEET @"retweeted_status"
#define CLUSER_REAL_NAME @"name"
#define CLUSER_SCREEN_NAME @"screen_name"
#define CLUSER_PROFILE_IMAGE_URL @"profile_image_url_https"